# The following properties are set in Jenkins:
# sonar.projectKey
# sonar.projectName
# sonar.branch.name
# sonar.ws.timeout
# Source location:
sonar.sources=.
sonar.scm.exclusions.disabled=true
sonar.inclusions=**/*.java,**/*.ts,**/*.js,**/*.css
sonar.sourceEncoding=UTF-8
sonar.java.source=25
sonar.java.binaries=.
sonar.javascript.node.maxspace=4096
sonar.exclusions=**/build/**/*
