# JACIS Continuous Integration GITHUB workflow
name: JACIS-Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     inputs:
      release:
        description: 'Release Build'     
        default: false


jobs:
  build-and-deploy:
    name: Build, Test and Deploy JACIS (release build ${{ github.event.inputs.release }})
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
#        os: [windows-latest, ubuntu-latest, macos-latest]
        java: [8]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build -Dreleasebuild=${{ github.event.inputs.release }}
    - name: Deploy ( to https://maven.pkg.github.com/janwiemer/jacis )
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish -Dreleasebuild=${{ github.event.inputs.release }} -Ddeploy_user=JanWiemer -Ddeploy_pw=${{secrets.GITHUB_TOKEN}} -Ddeploy_repo_release=https://maven.pkg.github.com/janwiemer/jacis -Ddeploy_repo_snapshot=https://maven.pkg.github.com/janwiemer/jacis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    