# JACIS Continuous Integration GITHUB workflow
name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      with:
        java-version: 11
      - name: Output
        run: echo Starting Continuous Integration Build for JACIS!
      - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build