# JACIS Continuous Integration GITHUB workflow
name: CI-Java-8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: JACIS CI Java 8
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assemble -Dreleasebuild=${{ github.event.inputs.release }} 
    - name: Test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build -Dreleasebuild=${{ github.event.inputs.release }}
    - name: Test Report
      uses: ashley-taylor/junit-report-annotations-action@1.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}