# JACIS Continuous Integration GITHUB workflow
name: JACIS-CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     inputs:
      release:
        description: 'Release Build'     
        default: false

jobs:
  build-and-test:
    name: Build and Test JACIS
    strategy:
      fail-fast: false
      matrix:
#        os: [windows-latest]
        os: [windows-latest, ubuntu-latest, macos-latest]
        java: [8, 11, 14]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Fix Permissions
      run: chmod +x gradlew
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build -Dreleasebuild=${{ github.event.inputs.release }}

  deploy:
    name: Deploy JACIS
    needs: build-and-test
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Deploy ( to https://maven.pkg.github.com/janwiemer/jacis )
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish -Dreleasebuild=${{ github.event.inputs.release }} -Ddeploy_user=JanWiemer -Ddeploy_pw=${{secrets.GITHUB_TOKEN}} -Ddeploy_repo_release=https://maven.pkg.github.com/janwiemer/jacis -Ddeploy_repo_snapshot=https://maven.pkg.github.com/janwiemer/jacis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    - name: Determine versions
      if: ${{ github.event.inputs.release }} == true
      uses: HardNorth/github-version-generate@v1.0.2
      with:
        version-source: file
        version-file: gradle.properties
        version-file-extraction-pattern: '(?<=version=).+'
    - name: Create Release
      if: ${{ github.event.inputs.release }} == true
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.RELEASE_VERSION }}"
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: |
            dependencies {
                implementation group: 'org.jacis', name: 'jacis', version: '${{ env.RELEASE_VERSION }}'
            }
        draft: false
        prerelease: false
