# JACIS Continuous Integration GITHUB workflow
name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     inputs:
      release:
        description: 'Release Build'     
        default: false


jobs:
  gradle:
    strategy:
      matrix:
        os: [windows-latest]
#        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish -Dreleasebuild=${{ github.event.inputs.release }} -Ddeploy_user=JanWiemer -Ddeploy_pw=${{secrets.GITHUB_TOKEN}} -Ddeploy_repo_release=https://maven.pkg.github.com/janwiemer/jacis -Ddeploy_repo_snapshot=https://maven.pkg.github.com/janwiemer/jacis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    