# JACIS Continuous Integration GITHUB workflow
name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [windows-latest]
#        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish -Ddeploy_repo_release=https://maven.pkg.github.com/JanWiemer/jacis -Ddeploy_repo_snapshot=https://maven.pkg.github.com/JanWiemer/jacis