# JACIS Continuous Integration GITHUB workflow
name: JACIS-CI-Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Test Action JACIS
    runs-on: windows-latest,
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Determine versions
      if: ${{ github.event.inputs.release }} ?= true
      uses: HardNorth/github-version-generate@v1.0.2
      with:
        version-source: file
        version-file: gradle.properties
        version-file-extraction-pattern: '(version *= *):.+'
